export function addParams(arr, id, country) {
  return arr.map((link) => {
    if (!link.includes("https://beliani.info/newsletter/2022/")) {
      if (!link.includes("https://upload.pictureserver.net/static/")) {
        return getQueryLink({ href: link }, id, country);
      }
    }
    return link;
  });
}

export function addParamsProduct(arr, id, country) {
  return arr.map((product) => ({
    ...product,
    href: getQueryLink(product, id, country),
  }));
}

export function addParamsCategory(arr, id, country) {
  return arr.map((category) => ({
    ...category,
    href: getQueryLink(category, id, country),
  }));
}

function getQueryLink(item, id, country) {

  if(item.href === undefined) return undefined

  const queryLink = new URL(item.href);

  if (item.query) {
      const link = new URL(item.href + item.query);
      for (const [key, value] of link.searchParams.entries()) {
          if (key.toLowerCase() in filterNames) {
              const newKey = filterNames[key.toLocaleLowerCase()][country];
              const newValue = filters[value.toLocaleLowerCase()][country];

              queryLink.searchParams.delete(key, value);
              queryLink.searchParams.set(newKey, newValue);
          }
      }
  }

  queryLink.searchParams.set("utm_source", "newsletter");
  queryLink.searchParams.set("utm_medium", "email");
  queryLink.searchParams.set("utm_campaign", id);

  return queryLink.href;
}

const filterNames = {
  style: {
    SE: "Stil",
    UK: "Style",
    FR: "Style",
    CHFR: "Style",
    IT: "Stile",
    CHDE: "Stil",
    DE: "Stil",
    AT: "Stil",
    HU: "Stílus",
    PT: "Estilo",
    FI: "Tyyli",
    ES: "Estilo",
    CZ: "Styl",
    NO: "Stil",
    NL: "Stijl",
    DK: "Stil",
    PL: "Styl",
    SK: "Styl",
  },
  sort: {
    SE: "sort",
    UK: "sort",
    FR: "sort",
    IT: "sort",
    CHDE: "sort",
    CHFR: "sort",
    DE: "sort",
    AT: "sort",
    HU: "sort",
    PT: "sort",
    FI: "sort",
    ES: "sort",
    CZ: "sort",
    NO: "sort",
    NL: "sort",
    DK: "sort",
    PL: "sort",
    SK: "sort",
  },
};

const filters = {
  boho: {
    SE: "Bohemisk",
    UK: "Boho",
    FR: "Boho",
    CHFR: "Boho",
    IT: "Boho",
    CHDE: "Boho",
    DE: "Boho",
    AT: "Boho",
    HU: "Boho",
    PT: "Boho",
    FI: "boho",
    ES: "Boho",
    CZ: "Boho",
    NO: "Boho",
    NL: "Boho",
    DK: "Boho",
    PL: "Boho",
    SK: "Boho",
  },
  glam: {
    CHDE: "Glamouros",
    DE: "Glamouros",
    AT: "Glamouros",
    UK: "Glam",
    SE: "Glam",
    HU: "Glam",
    CZ: "Glam",
    DK: "Glam",
    NO: "Glam",
    FR: "Glamour",
    CHFR: "Glamour",
    IT: "Glamour",
    PT: "Glamour",
    FI: "glamour",
    ES: "Glamour",
    PL: "Glamour",
    SK: "Glamour",
    NL: "Glamoureus",
  },
  industrial: {
    FI: "industriaalinen",
    UK: "Industrial",
    IT: "Industriale",
    PT: "Industrial",
    PL: "Industrialny",
    ES: "Industrial",
    SK: "Industrialny",
    NL: "Industrieel",
    FR: "Industriel",
    CHFR: "Industriel",
    CHDE: "Industriell",
    DE: "Industriell",
    AT: "Industriell",
    SE: "Industriell",
    DK: "Industriel",
    NO: "Industriell",
    HU: "Ipari",
    CZ: "Prumyslovy",
  },
  modern: {
    UK: "Modern",
    CHDE: "Modern",
    DE: "Modern",
    AT: "Modern",
    SE: "Modern",
    HU: "Modern",
    NL: "Modern",
    FR: "Moderne",
    CHFR: "Moderne",
    DK: "Moderne",
    NO: "Moderne",
    FI: "moderni",
    CZ: "Moderni",
    IT: "Moderno",
    PT: "Moderno",
    ES: "Moderno",
    SK: "Moderny",
    PL: "Nowoczesny",
  },
  retro: {
    UK: "Retro",
    FR: "Retro",
    CHFR: "Retro",
    IT: "Retro",
    CHDE: "Retro",
    DE: "Retro",
    AT: "Retro",
    SE: "Retro",
    HU: "Retro",
    PT: "Retro",
    FI: "retro",
    ES: "Retro",
    CZ: "Retro",
    PL: "Retro",
    NL: "Retro",
    DK: "Retro",
    SK: "Retro",
    NO: "Retro",
  },
  rustic: {
    UK: "Rustic",
    IT: "Rustico",
    PT: "Rústico",
    ES: "Rústico",
    NL: "Rustiek",
    FI: "rustiikkinen",
    SE: "Rustik",
    DK: "Rustik",
    CHDE: "Rustikal",
    DE: "Rustikal",
    AT: "Rustikal",
    CZ: "Rustikalni",
    SK: "Rustikalni",
    NO: "Rustikk",
    FR: "Rustique",
    CHFR: "Rustique",
    PL: "Rustykalny",
    HU: "Rusztikus",
  },
  scandinavian: {
    PT: "Escandinavo",
    ES: "Escandinavo",
    FR: "Scandinave",
    CHFR: "Scandinave",
    UK: "Scandinavian",
    NL: "Scandinavisch",
    IT: "Scandinavo",
    FI: "skandinaavinen",
    HU: "Skandinav",
    CHDE: "Skandinavisch",
    DE: "Skandinavisch",
    SE: "Skandinavisk",
    DK: "Skandinavisk",
    NO: "Skandinavisk",
    CZ: "Skandinavsky",
    SK: "Skandinavsky",
    PL: "Skandynawski",
  },
  traditional: {
    IT: "Classico",
    CHDE: "Klassisch",
    DE: "Klassisch",
    AT: "Klassisch",
    NO: "Klassisk",
    HU: "Klasszikus",
    PL: "Klasyczny",
    FI: "perinteinen",
    PT: "Tradicional",
    ES: "Tradicional",
    CZ: "Tradicni",
    SK: "Tradicny",
    UK: "Traditional",
    SE: "Traditionell",
    NL: "Traditioneel",
    DK: "Traditionel",
    FR: "Traditionnel",
    CHFR: "Traditionnel",
  },
  newest: {
    IT: "newest",
    CHDE: "newest",
    DE: "newest",
    AT: "newest",
    NO: "newest",
    HU: "newest",
    PL: "newest",
    FI: "newest",
    PT: "newest",
    ES: "newest",
    CZ: "newest",
    SK: "newest",
    UK: "newest",
    SE: "newest",
    NL: "newest",
    DK: "newest",
    FR: "newest",
    CHFR: "newest",
  },
  lowest_price: {
    IT: "lowest_price",
    CHDE: "lowest_price",
    DE: "lowest_price",
    AT: "lowest_price",
    NO: "lowest_price",
    HU: "lowest_price",
    PL: "lowest_price",
    FI: "lowest_price",
    PT: "lowest_price",
    ES: "lowest_price",
    CZ: "lowest_price",
    SK: "lowest_price",
    UK: "lowest_price",
    SE: "lowest_price",
    NL: "lowest_price",
    DK: "lowest_price",
    FR: "lowest_price",
    CHFR: "lowest_price",
  },
  highest_price: {
    IT: "highest_price",
    CHDE: "highest_price",
    DE: "highest_price",
    AT: "highest_price",
    NO: "highest_price",
    HU: "highest_price",
    PL: "highest_price",
    FI: "highest_price",
    PT: "highest_price",
    ES: "highest_price",
    CZ: "highest_price",
    SK: "highest_price",
    UK: "highest_price",
    SE: "highest_price",
    NL: "highest_price",
    DK: "highest_price",
    FR: "highest_price",
    CHFR: "highest_price",
  },
  best_rated: {
    IT: "best_rated",
    CHDE: "best_rated",
    DE: "best_rated",
    AT: "best_rated",
    NO: "best_rated",
    HU: "best_rated",
    PL: "best_rated",
    FI: "best_rated",
    PT: "best_rated",
    ES: "best_rated",
    CZ: "best_rated",
    SK: "best_rated",
    UK: "best_rated",
    SE: "best_rated",
    NL: "best_rated",
    DK: "best_rated",
    FR: "best_rated",
    CHFR: "best_rated",
  },
  default: {
    IT: "default",
    CHDE: "default",
    DE: "default",
    AT: "default",
    NO: "default",
    HU: "default",
    PL: "default",
    FI: "default",
    PT: "default",
    ES: "default",
    CZ: "default",
    SK: "default",
    UK: "default",
    SE: "default",
    NL: "default",
    DK: "default",
    FR: "default",
    CHFR: "default",
  },
};
