import { getState } from "../main/initApp.js";
import origins from "../data/templates/origins.js";

export function addParams(arr) {
  const country = getState("country");

  return arr.map((link) => {
    if ("query" in link) {
      return getQueryLink({
        href: link.value(origins[country], country.toLowerCase()),
      });
    }
    return typeof link === "object"
      ? link.value(origins[country], country.toLowerCase())
      : link;
  });
}

export function addParamsProduct(product) {
  return {
    ...product,
    href: getQueryLink(product),
  };
}

export function getQueryLink(item) {
  const template = getState("template");
  const country = getState("country");
  const ids = getState("ids");

  if (item.href === undefined) return undefined;
  if (item.href === null) return undefined;

  const queryLink = new URL(item.href);

  // Category query
  if (item.searchParams) {
    for (const [key, value] of item.searchParams.entries()) {
      if (key.toLowerCase() in filterNames) {
        const newKey = filterNames[key.toLocaleLowerCase()][country];
        const allFilters = item.searchParams.get(key).split(",");

        queryLink.searchParams.delete(key, value);
        allFilters.forEach((item) => {
          const newValue = filters[item.toLocaleLowerCase()][country];
          queryLink.searchParams.append(newKey, newValue);
        });
      }
    }
  }

  if (template === "newsletter") {
    queryLink.searchParams.set("utm_source", "newsletter");
    queryLink.searchParams.set("utm_medium", "email");
    queryLink.searchParams.set("utm_campaign", ids[country]);
  }

  return queryLink.href;
}
const filterNames = {
  style: {
    SE: "Stil",
    UK: "Style",
    FR: "Style",
    CHFR: "Style",
    IT: "Stile",
    CHDE: "Stil",
    DE: "Stil",
    AT: "Stil",
    HU: "Stílus",
    PT: "Estilo",
    FI: "Tyyli",
    ES: "Estilo",
    CZ: "Styl",
    NO: "Stil",
    NL: "Stijl",
    DK: "Stil",
    PL: "Styl",
    SK: "Styl",
  },
  sort: {
    SE: "sort",
    UK: "sort",
    FR: "sort",
    IT: "sort",
    CHDE: "sort",
    CHFR: "sort",
    DE: "sort",
    AT: "sort",
    HU: "sort",
    PT: "sort",
    FI: "sort",
    ES: "sort",
    CZ: "sort",
    NO: "sort",
    NL: "sort",
    DK: "sort",
    PL: "sort",
    SK: "sort",
  },
  material: {
    SE: "Material",
    UK: "Material",
    FR: "Matiere",
    IT: "Materiale",
    CHDE: "Matiere",
    CHFR: "Material",
    DE: "Material",
    AT: "Material",
    HU: "Anyag_tipusa",
    PT: "Material",
    FI: "Materiaali",
    ES: "Material",
    CZ: "Material",
    NO: "Materiale",
    NL: "Materiaal",
    DK: "Materiale",
    PL: "Material",
    SK: "Material",
  },
  features: {
    SE: "Egenskaper",
    UK: "Features",
    FR: "Caracteristiques",
    IT: "Caratteristiche",
    CHDE: "Merkmale",
    CHFR: "Caracteristiques",
    DE: "Merkmale",
    AT: "Merkmale",
    HU: "Fobb_jellemzok",
    PT: "Caracteristicas",
    FI: "Ominaisuudet",
    ES: "Caracteristicas",
    CZ: "Vlastnosti",
    NO: "Egenskaper",
    NL: "Eigenschappen",
    DK: "Funktioner",
    PL: "Cechy",
    SK: "Vlastnosti",
  },
  colour: {
    SE: "Farg",
    UK: "Colour",
    FR: "Couleur",
    IT: "Colore",
    CHDE: "Farbe",
    CHFR: "Couleur",
    DE: "Farbe",
    AT: "Farbe",
    HU: "Szin",
    PT: "Cor",
    FI: "Vari",
    ES: "Color",
    CZ: "Barva",
    NO: "Farge",
    NL: "Kleur",
    DK: "Farve",
    PL: "Kolor",
    SK: "Farba",
  },
};
const filters = {
  red: {
    SE: "Rod",
    UK: "Red",
    FR: "Rouge",
    CHFR: "Rouge",
    IT: "Rosso",
    CHDE: "Rot",
    DE: "Rot",
    AT: "Rot",
    HU: "Piros",
    PT: "Vermelho",
    FI: "Punainen",
    ES: "Rojo",
    CZ: "Cervena",
    NO: "Rod",
    NL: "Rood",
    DK: "Rod",
    PL: "Czerwony",
    SK: "Cervena",
  },
  pink: {
    SE: "Rosa",
    UK: "Pink",
    FR: "Rose",
    CHFR: "Rose",
    IT: "Rosa",
    CHDE: "Rosa",
    DE: "Rosa",
    AT: "Rosa",
    HU: "Rozsaszin",
    PT: "Rosa",
    FI: "Vaaleanpunainen",
    ES: "Rosa",
    CZ: "Ruzova",
    NO: "Rosa",
    NL: "Roze",
    DK: "Lyserod",
    PL: "Rozowy",
    SK: "Ruzova",
  },
  green: {
    SE: "Gron",
    UK: "Green",
    FR: "Vert",
    CHFR: "Vert",
    IT: "Verde",
    CHDE: "Grun",
    DE: "Grun",
    AT: "Grun",
    HU: "Zold",
    PT: "Verde",
    FI: "Vihrea",
    ES: "Verde",
    CZ: "Zelena",
    NO: "Gronn",
    NL: "Groen",
    DK: "Gron",
    PL: "Zielony",
    SK: "Zelena",
  },
  orange: {
    SE: "Orange",
    UK: "Orange",
    FR: "Orange",
    CHFR: "Orange",
    IT: "Arancione",
    CHDE: "Orange",
    DE: "Orange",
    AT: "Orange",
    HU: "Narancssarga",
    PT: "Laranja",
    FI: "Oranssi",
    ES: "Naranja",
    CZ: "Oranzova",
    NO: "Oransje_",
    NL: "Oranje",
    DK: "Orange",
    PL: "Pomaranczowy",
    SK: "Oranzova",
  },
  yellow: {
    SE: "Gul",
    UK: "Yellow",
    FR: "Jaune",
    CHFR: "Jaune",
    IT: "Giallo",
    CHDE: "Gelb",
    DE: "Gelb",
    AT: "Gelb",
    HU: "Sarga",
    PT: "Amarelo",
    FI: "Keltainen",
    ES: "Amarillo",
    CZ: "Zluta",
    NO: "Gul",
    NL: "Geel",
    DK: "Gul",
    PL: "Zolty",
    SK: "Zlta",
  },
  violet: {
    SE: "Morklila",
    UK: "Violet",
    FR: "Violet",
    CHFR: "Violet",
    IT: "Viola",
    CHDE: "Violett",
    DE: "Violett",
    AT: "Violett",
    HU: "Lila",
    PT: "Violeta",
    FI: "Violetti",
    ES: "Violeta",
    CZ: "Fialova",
    NO: "Fiolett",
    NL: "Paars",
    DK: "Lilla",
    PL: "Fioletowy",
    SK: "Fialova",
  },
  boho: {
    SE: "Bohemisk",
    UK: "Boho",
    FR: "Boho",
    CHFR: "Boho",
    IT: "Boho",
    CHDE: "Boho",
    DE: "Boho",
    AT: "Boho",
    HU: "Boho",
    PT: "Boho",
    FI: "boho",
    ES: "Boho",
    CZ: "Boho",
    NO: "Boho",
    NL: "Boho",
    DK: "Boho",
    PL: "Boho",
    SK: "Boho",
  },
  glam: {
    CHDE: "Glamouros",
    DE: "Glamouros",
    AT: "Glamouros",
    UK: "Glam",
    SE: "Glam",
    HU: "Glam",
    CZ: "Glam",
    DK: "Glam",
    NO: "Glam",
    FR: "Glamour",
    CHFR: "Glamour",
    IT: "Glamour",
    PT: "Glamour",
    FI: "glamour",
    ES: "Glamour",
    PL: "Glamour",
    SK: "Glamour",
    NL: "Glamoureus",
  },
  industrial: {
    FI: "industriaalinen",
    UK: "Industrial",
    IT: "Industriale",
    PT: "Industrial",
    PL: "Industrialny",
    ES: "Industrial",
    SK: "Industrialny",
    NL: "Industrieel",
    FR: "Industriel",
    CHFR: "Industriel",
    CHDE: "Industriell",
    DE: "Industriell",
    AT: "Industriell",
    SE: "Industriell",
    DK: "Industriel",
    NO: "Industriell",
    HU: "Ipari",
    CZ: "Prumyslovy",
  },
  modern: {
    UK: "Modern",
    CHDE: "Modern",
    DE: "Modern",
    AT: "Modern",
    SE: "Modern",
    HU: "Modern",
    NL: "Modern",
    FR: "Moderne",
    CHFR: "Moderne",
    DK: "Moderne",
    NO: "Moderne",
    FI: "moderni",
    CZ: "Moderni",
    IT: "Moderno",
    PT: "Moderno",
    ES: "Moderno",
    SK: "Moderny",
    PL: "Nowoczesny",
  },
  retro: {
    UK: "Retro",
    FR: "Retro",
    CHFR: "Retro",
    IT: "Retro",
    CHDE: "Retro",
    DE: "Retro",
    AT: "Retro",
    SE: "Retro",
    HU: "Retro",
    PT: "Retro",
    FI: "retro",
    ES: "Retro",
    CZ: "Retro",
    PL: "Retro",
    NL: "Retro",
    DK: "Retro",
    SK: "Retro",
    NO: "Retro",
  },
  rustic: {
    UK: "Rustic",
    IT: "Rustico",
    PT: "Rústico",
    ES: "Rústico",
    NL: "Rustiek",
    FI: "rustiikkinen",
    SE: "Rustik",
    DK: "Rustik",
    CHDE: "Rustikal",
    DE: "Rustikal",
    AT: "Rustikal",
    CZ: "Rustikalni",
    SK: "Rustikalni",
    NO: "Rustikk",
    FR: "Rustique",
    CHFR: "Rustique",
    PL: "Rustykalny",
    HU: "Rusztikus",
  },
  scandinavian: {
    PT: "Escandinavo",
    ES: "Escandinavo",
    FR: "Scandinave",
    CHFR: "Scandinave",
    UK: "Scandinavian",
    NL: "Scandinavisch",
    IT: "Scandinavo",
    FI: "skandinaavinen",
    HU: "Skandinav",
    CHDE: "Skandinavisch",
    DE: "Skandinavisch",
    SE: "Skandinavisk",
    DK: "Skandinavisk",
    NO: "Skandinavisk",
    CZ: "Skandinavsky",
    SK: "Skandinavsky",
    PL: "Skandynawski",
  },
  traditional: {
    IT: "Classico",
    CHDE: "Klassisch",
    DE: "Klassisch",
    AT: "Klassisch",
    NO: "Klassisk",
    HU: "Klasszikus",
    PL: "Klasyczny",
    FI: "perinteinen",
    PT: "Tradicional",
    ES: "Tradicional",
    CZ: "Tradicni",
    SK: "Tradicny",
    UK: "Traditional",
    SE: "Traditionell",
    NL: "Traditioneel",
    DK: "Traditionel",
    FR: "Traditionnel",
    CHFR: "Traditionnel",
  },
  newest: {
    IT: "newest",
    CHDE: "newest",
    DE: "newest",
    AT: "newest",
    NO: "newest",
    HU: "newest",
    PL: "newest",
    FI: "newest",
    PT: "newest",
    ES: "newest",
    CZ: "newest",
    SK: "newest",
    UK: "newest",
    SE: "newest",
    NL: "newest",
    DK: "newest",
    FR: "newest",
    CHFR: "newest",
  },
  lowest_price: {
    IT: "lowest_price",
    CHDE: "lowest_price",
    DE: "lowest_price",
    AT: "lowest_price",
    NO: "lowest_price",
    HU: "lowest_price",
    PL: "lowest_price",
    FI: "lowest_price",
    PT: "lowest_price",
    ES: "lowest_price",
    CZ: "lowest_price",
    SK: "lowest_price",
    UK: "lowest_price",
    SE: "lowest_price",
    NL: "lowest_price",
    DK: "lowest_price",
    FR: "lowest_price",
    CHFR: "lowest_price",
  },
  highest_price: {
    IT: "highest_price",
    CHDE: "highest_price",
    DE: "highest_price",
    AT: "highest_price",
    NO: "highest_price",
    HU: "highest_price",
    PL: "highest_price",
    FI: "highest_price",
    PT: "highest_price",
    ES: "highest_price",
    CZ: "highest_price",
    SK: "highest_price",
    UK: "highest_price",
    SE: "highest_price",
    NL: "highest_price",
    DK: "highest_price",
    FR: "highest_price",
    CHFR: "highest_price",
  },
  best_rated: {
    IT: "best_rated",
    CHDE: "best_rated",
    DE: "best_rated",
    AT: "best_rated",
    NO: "best_rated",
    HU: "best_rated",
    PL: "best_rated",
    FI: "best_rated",
    PT: "best_rated",
    ES: "best_rated",
    CZ: "best_rated",
    SK: "best_rated",
    UK: "best_rated",
    SE: "best_rated",
    NL: "best_rated",
    DK: "best_rated",
    FR: "best_rated",
    CHFR: "best_rated",
  },
  default: {
    IT: "default",
    CHDE: "default",
    DE: "default",
    AT: "default",
    NO: "default",
    HU: "default",
    PL: "default",
    FI: "default",
    PT: "default",
    ES: "default",
    CZ: "default",
    SK: "default",
    UK: "default",
    SE: "default",
    NL: "default",
    DK: "default",
    FR: "default",
    CHFR: "default",
  },
  fabric: {
    IT: "Tessuto",
    CHDE: "Stoff",
    DE: "Stoff",
    AT: "Stoff",
    NO: "Stoff",
    HU: "Anyag",
    PL: "Tkanina",
    FI: "kangas",
    PT: "Tecido",
    ES: "Tejido",
    CZ: "Tkanina",
    SK: "Textil",
    UK: "Fabric",
    SE: "Tyg",
    NL: "Stof",
    DK: "Stof",
    FR: "Tissu",
    CHFR: "Tissu",
  },
  metal: {
    IT: "Metallo",
    CHDE: "Metall",
    DE: "Metall",
    AT: "Metall",
    NO: "Metal",
    HU: "Fem",
    PL: "Metal",
    FI: "metalli",
    PT: "Metal",
    ES: "Metal",
    CZ: "Kov",
    SK: "Kov",
    UK: "Metal",
    SE: "Metall",
    NL: "Metaal",
    DK: "Metal",
    FR: "Metal",
    CHFR: "Metal",
  },
  rattan: {
    IT: "Rattan_sintetico",
    CHDE: "Rattan",
    DE: "Rattan",
    AT: "Rattan",
    NO: "Rotting",
    HU: "Rattan",
    PL: "Rattan",
    FI: "rottinki",
    PT: "Rattan",
    ES: "Mimbre_sintetico",
    CZ: "Ratan",
    SK: "Ratan",
    UK: "Rattan",
    SE: "Rotting",
    NL: "Rotan",
    DK: "Rattan",
    FR: "Rotin",
    CHFR: "Rotin",
  },
  pe_rattan: {
    IT: "Rattan_sintetico",
    CHDE: "PE_Rattan",
    DE: "PE_Rattan",
    AT: "PE_Rattan",
    NO: "Kunstrotting",
    HU: "Szintetikus_rattan",
    PL: "Technorattan",
    FI: "polyrottinki",
    PT: "Ratan_sintetico",
    ES: "Ratan_sintetico",
    CZ: "Umely_ratan",
    SK: "Umely_ratan",
    UK: "PE_Rattan",
    SE: "Konstrotting",
    NL: "PE_rotan",
    DK: "PE_Rattan",
    FR: "Polyrotin",
    CHFR: "Polyrotin",
  },
  synthetic_material: {
    IT: "",
    CHDE: "",
    DE: "",
    AT: "",
    NO: "",
    HU: "",
    PL: "",
    FI: "",
    PT: "",
    ES: "",
    CZ: "",
    SK: "",
    UK: "Synthetic_Material",
    SE: "",
    NL: "",
    DK: "",
    FR: "",
    CHFR: "",
  },
  wood: {
    IT: "",
    CHDE: "",
    DE: "",
    AT: "",
    NO: "",
    HU: "",
    PL: "",
    FI: "",
    PT: "",
    ES: "",
    CZ: "",
    SK: "",
    UK: "Wood",
    SE: "",
    NL: "",
    DK: "",
    FR: "",
    CHFR: "",
  },
  marble_effect_finish: {
    IT: "Finitura_effetto_marmo",
    CHDE: "Marmor_Optik",
    DE: "Marmor_Optik",
    AT: "Marmor_Optik",
    NO: "Marmoreffekt",
    HU: "Marvanyhatasu_felulet",
    PL: "Z_efektem_marmuru",
    FI: "marmorimainen_viimeistely",
    PT: "Acabamento_com_efeito_de_marmore",
    ES: "Acabado_efecto_marmol",
    CZ: "Povrch_s_mramorovym_efektem",
    SK: "Povrch_s_mramorovym_efektom",
    UK: "Marble_Effect_Finish",
    SE: "Marmoreffekt",
    NL: "Gemarmerde_afwerking",
    DK: "Marmor_effekt_finish",
    FR: "Finition_effet_marbre",
    CHFR: "Finition_effet_marbre",
  },
};
